import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../providers/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </head>
      <body>
        {/*
          By using our new 'Providers' component, we ensure all children
          are correctly wrapped in the necessary client-side contexts.
          This is much cleaner than nesting providers directly in this file.
        */}
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
